{% set name = "fastnumbers" %}
{% set version = "5.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 183fa021cdc052edaeede5c23e3086461deb7562b567614edf71b29515f5fa4b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - fastnumbers

about:
  home: https://github.com/SethMMorton/fastnumbers
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Super-fast and clean conversions to numbers.
  dev_url: https://github.com/SethMMorton/fastnumbers
  doc_url: https://fastnumbers.readthedocs.io/

extra:
  recipe-maintainers:
    - synapticarbors
    - pmlandwehr
    - lucventurini
