context:
  name: fastnumbers
  version: 5.1.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 183fa021cdc052edaeede5c23e3086461deb7562b567614edf71b29515f5fa4b

build:
  number: 1
  skip: "python_impl == 'pypy'"
  script: python -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

tests:
  - python:
      imports:
        - fastnumbers
      pip_check: false

about:
  license_file: LICENSE
  license: MIT
  summary: Super-fast and clean conversions to numbers.
  homepage: https://github.com/SethMMorton/fastnumbers
  repository: https://github.com/SethMMorton/fastnumbers
  documentation: https://fastnumbers.readthedocs.io/

extra:
  recipe-maintainers:
    - synapticarbors
    - pmlandwehr
    - lucventurini
