travis:
  secure:
    BINSTAR_TOKEN: Qwrpv5MDn4UQVuhbATv5RpS/bgUP/A/MZHXfpfPIb+j1GgXZEG/BGbT0n0qMGMT4091djmwvf8pkvV/kk55vCAl8vN59smaeW2RjDJPhqp87dA440yhbgXE2PY1vq/ei1wpgGAn72LBa2XbhwpLHEqinsZtVA9nSXr6OcrZSyk8z9rqF3XagT/3Wq9Mgrb7Diew3A+mCzDfCdr5txL0OsArVcUXB6cIzLlJxlqPSg15V+8OukxqJ0eaizX3e4byW0KD02c3XNH9vc1mstk/QpA8LfZhJgFbgCU9rIIxdLPl5gIJejjgXcrMUI33TS55sSID41VX8QDrXHfihK9e0h8HyDEhaNmNcAq6KSfYZpHDaJpu64bSFxjXskjXtGK07rqLvRAR2yTmL76jebbCqG2ys+tY3wKzCML4d9RO5DZUnehQO15RUx4cnPWLzLxsskdG74WfoMPGIvJ29ICclBVoZA8V/0iBc/aRFii+9kxB3jYE/4DVaQrIeWty8h1p3etynydr4rd4qFKy+RiYDNgy0k1r9d1bOcyfTIiabTKg9ysKNBMi9I3l2Px1lOtpm4+2amD7zyT8AblzcAlqQs/idm8LBMfa1R4RYMVNv5m4U0ame+Kjp5Lu9w4BxzHszXUYP19SjbVIFg7X2B1M1Q/cO25p05BB5h9fs5ht4vGc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
